In [1]:
import pandas as pd

# Importing Files

## 1. Working with csv files

https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

### Opening local csv file

In [9]:
df = pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv')
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### Opening a csv file from an URL

In [11]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

### sep Parameter
When we want to specify based on which symbol we do separation.

In [13]:
pd.read_csv('Datasets/1-Data-Gathering/movie_titles_metadata.tsv', sep='\t')

# here we can see that we do not have a column names so for this we have another paramter called names.

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

### name Parameter

In [14]:
pd.read_csv('Datasets/1-Data-Gathering/movie_titles_metadata.tsv', sep='\t', names=['sno', 'name', 'release_year', 'rating', 'votes', 'genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

### index_col Parameter

In [18]:
pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv', index_col='enrollee_id').head()

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### header Parameter

In [20]:
pd.read_csv('Datasets/1-Data-Gathering/test.csv').head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [21]:
# here we can see that our column names are treated as a rows, so to make them column names again we use header parameter
pd.read_csv('Datasets/1-Data-Gathering/test.csv', header=1).head()

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

### use_cols Parameter
When we want to use specific cols while importing

In [24]:
pd.read_csv('Datasets/1-Data-Gathering/test.csv', header=1, usecols=['enrollee_id', 'gender', 'education_level']).head()

   enrollee_id gender education_level
0        29725   Male        Graduate
1        11561    NaN        Graduate
2        33241    NaN        Graduate
3          666   Male         Masters

### squeeze Method
When we want only one columns means it converts the dataframe into a series

In [33]:
temp = pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv', usecols=['gender']).squeeze()
print(temp)
print(type(temp)) # series

0        Male
1        Male
2         NaN
3         NaN
4        Male
         ...
19153    Male
19154    Male
19155    Male
19156    Male
19157     NaN
Name: gender, Length: 19158, dtype: object
<class 'pandas.core.series.Series'>

### skiprows/nrows Parameter

In [35]:
pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv').head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [36]:
pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv', skiprows=[0, 1]) # first two rows are skipped

,29725,city_40,0.7759999999999999,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19155,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [37]:
# we can also use our own logic inside the skiprows parameter using lambda
pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv', skiprows=lambda x: x % 2 == 0 and x != 0) # for even rows

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
4,27107,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,7,50-99,Pvt Ltd,1,46,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9574,9212,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,3,100-500,Pvt Ltd,3,40,1.0
9575,32313,city_160,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,10,100-500,Public Sector,3,23,0.0
9576,29754,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,Humanities,7,10/49,Funded Startup,1,25,0.0
9577,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
9578,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0

In [38]:
# nrows (Number of rows needed)
pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv', nrows=100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

### encoding Parameter

Some CSV files are saved using encodings other than UTF-8 (such as `latin-1`, `ISO-8859-1`, or `cp1252`). In such cases, we use the `encoding` parameter in `pd.read_csv()` to tell pandas how to correctly read the file.

In [41]:
pd.read_csv('Datasets/1-Data-Gathering/zomato.csv', encoding='latin-1').head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

### on_bad_lines (Skip bad lines)
A bad line is a row that doesn't match the expected format. For example, if the CSV should have 3 columns, but one row has 4 columns, that row is considered bad.

In [48]:
pd.read_csv('Datasets/1-Data-Gathering/BX-Books.csv', sep=';', encoding='latin-1', on_bad_lines='skip')

       isbn,book_title,book_author,year_of_publication,publisher
0       195153448,Classical Mythology,Mark P. O. Morfo...
1       2005018,Clara Callan,Richard Bruce Wright,2001...
2       60973129,Decision in Normandy,Carlo D'Este,199...
3       374157065,Flu: The Story of the Great Influenz...
4       399135782,The Kitchen God's Wife,Amy Tan,1991,...
...                                                   ...
249950  440400988,There's a Bat in Bunk Five,Paula Dan...
249951  525447644,From One to One Hundred,Teri Sloat,1...
249952  006008667X,Lily Dale : The True Story of the T...
249953  192126040,Republic (World's Classics),Plato,19...
249954  767409752,A Guided Tour of Rene Descartes' Med...

[249955 rows x 1 columns]

### dtype Parameter

In [51]:
pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv').head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [56]:
# converting the data type of target col
pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv', dtype={'target':int}).head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

### Handling Dates (parse_dates)

In [59]:
pd.read_csv('Datasets/1-Data-Gathering/IPL Matches 2008-2020.csv').head()

# here the dates are strings

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [62]:
# now to convert them to date we will use parse_date parameter

pd.read_csv('Datasets/1-Data-Gathering/IPL Matches 2008-2020.csv', parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

### convertors Parameter
used in file-reading functions like pandas.read_csv that accepts a dictionary mapping column names or indices to custom function

In [66]:
def rename(name):
    if name == 'Royal Challengers Bangalore':
        return 'RCB'
    else:
        return name

In [67]:
rename('Royal Challengers Bangalore')

'RCB'

In [68]:
pd.read_csv('Datasets/1-Data-Gathering/IPL Matches 2008-2020.csv', converters={'team1': rename}).head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

### na_values Parameter
to specify additional strings, numbers, or symbols that should be recognized as missing data (NaN)

In [71]:
# example if we specify the Male as na value

pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv', na_values=['Male']).head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### Loading a dataset in chunks

In [86]:
dfs = pd.read_csv('Datasets/1-Data-Gathering/aug_train.csv', chunksize=5000)
dfs

In [87]:
for chunks in dfs:
    print(chunks.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)

## 2. Import data from excel files

In [ ]:
pd.read_excel('output.xlsx', index_col='Unnamed: 0')

# If excel has two sheets this will automatically fetch the first one

### sheet_name Parameter

In [ ]:
# If we want the second one
pd.read_excel('output.xlsx', sheet_name='Sheet_2')

### Most of the parameters are same as csv files

## 3. Reading text files

In [ ]:
# We will check the structure of text file and see how our data is separated.
pd.read_csv('question_answer_pairs.txt', sep='\t')

# so the separation is based on tabs

### Most of the parameters are same as csv files

## 4. Reading JSON files

In [93]:
pd.read_json('Datasets/1-Data-Gathering/train.json').head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [2]:
# fetching json data from an api
df = pd.read_json("https://jsonplaceholder.typicode.com/users")
df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

### Most of the parameters are same as csv files

## 5. Reading SQL files

First we have to run our Xampp Server and load our sql data inside a database.

In [3]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 1.9 MB/s eta 0:00:06
     ------ --------------------------------- 1.8/11.9 MB 4.5 MB/s eta 0:00:03
     -------- ------------------------------- 2.6/11.9 MB 5.0 MB/s eta 0:00:02
     -------- ------------------------------- 2.6/11.9 MB 5.0 MB/s eta 0:00:02
     ----------- ---------------------------- 3.4/11.9 MB 3.9 MB/s eta 0:00:03
     ---------------- ----------------------- 5.0/11.9 MB 4.1 MB/s eta 0:00:02
     ----------------- ---------------------- 5.2/11.9 MB 3.9 MB/s eta 0:00:02
     -------------------- ------------------- 6.0/11.9 MB 4.0 MB/s eta 0:00:02
     ---------------------- ----------------- 6.6/11.9 MB 3.9 MB/s eta 0:00:02
     ---------------------- ----------------- 6.6/11.9 MB 3.9 MB/s eta 0:00:02
     -------------------------- ------------- 7.9/11.9 MB 3.7 MB/s eta 0:00:02
     -------------------------- ------------- 7.9/11.9 MB 3.7 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 3.5 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 3.5 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 3.5 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 3.4 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 3.4 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.2 MB/s  0:00:04
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=67145aa5acbcc755e32ad9720aeafd9918dbb8255eb4b881d6d011afcae46fd0
  Stored in directory: c:\users\mwale\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [4]:
import mysql.connector

In [ ]:
conn = msql.connector.connector(host='localhost', user='root', password='', database='world')

# by running this we get a connection object

In [ ]:
pd.read_sql_query('SELECT * FROM city') # (sql query, connection)

In [ ]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'USA'", conn)

In [ ]:
pd.read_sql_query("SELECT * FROM country", conn)

In [ ]:
pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 60", conn)

### Most of the parameters are same as csv files

# Exporting Files

### 1. CSV

In [10]:
df = pd.read_csv('Datasets/1-Data-Gathering/deliveries.csv')
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [19]:
temp_df = df.groupby('batsman')['batsman_runs'].sum().reset_index()

temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4        A Flintoff            62
..              ...           ...
456     YV Takawale           192
457   Yashpal Singh            47
458     Younis Khan             3
459    Yuvraj Singh          2591
460          Z Khan           117

[461 rows x 2 columns]

In [24]:
temp_df.to_csv('Datasets/1-Data-Gathering/batsman_runs.csv', index=False)

In [28]:
temp_df2 = df.pivot_table(index='batsman', columns='bowling_team', values='batsman_runs', aggfunc='sum')
temp_df2

bowling_team,Chennai Super Kings,Deccan Chargers,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
batsman,,,,,,,,,,,,,,
A Ashish Reddy,45.0,NaN,36.0,NaN,37.0,NaN,17.0,27.0,26.0,37.0,NaN,NaN,55.0,NaN
A Chandila,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
A Chopra,NaN,35.0,13.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN
A Choudhary,NaN,NaN,NaN,15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
A Flintoff,NaN,NaN,16.0,NaN,NaN,NaN,NaN,24.0,NaN,NaN,NaN,NaN,22.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YV Takawale,19.0,5.0,14.0,NaN,0.0,NaN,85.0,NaN,NaN,69.0,NaN,NaN,NaN,NaN
Yashpal Singh,NaN,NaN,13.0,NaN,NaN,NaN,NaN,8.0,NaN,26.0,NaN,NaN,NaN,NaN
Younis Khan,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yuvraj Singh,321.0,118.0,433.0,13.0,239.0,8.0,386.0,259.0,NaN,384.0,47.0,23.0,312.0,48.0
Z Khan,39.0,4.0,4.0,NaN,1.0,NaN,20.0,5.0,NaN,18.0,NaN,NaN,25.0,1.0

In [29]:
temp_df2.to_csv('Datasets/1-Data-Gathering/batsman_vs_teams.csv')

### 2. Excel

In [30]:
temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4        A Flintoff            62
..              ...           ...
456     YV Takawale           192
457   Yashpal Singh            47
458     Younis Khan             3
459    Yuvraj Singh          2591
460          Z Khan           117

[461 rows x 2 columns]

In [33]:
temp_df2

bowling_team,Chennai Super Kings,Deccan Chargers,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Sunrisers Hyderabad
batsman,,,,,,,,,,,,,,
A Ashish Reddy,45.0,NaN,36.0,NaN,37.0,NaN,17.0,27.0,26.0,37.0,NaN,NaN,55.0,NaN
A Chandila,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
A Chopra,NaN,35.0,13.0,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN
A Choudhary,NaN,NaN,NaN,15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
A Flintoff,NaN,NaN,16.0,NaN,NaN,NaN,NaN,24.0,NaN,NaN,NaN,NaN,22.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YV Takawale,19.0,5.0,14.0,NaN,0.0,NaN,85.0,NaN,NaN,69.0,NaN,NaN,NaN,NaN
Yashpal Singh,NaN,NaN,13.0,NaN,NaN,NaN,NaN,8.0,NaN,26.0,NaN,NaN,NaN,NaN
Younis Khan,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yuvraj Singh,321.0,118.0,433.0,13.0,239.0,8.0,386.0,259.0,NaN,384.0,47.0,23.0,312.0,48.0
Z Khan,39.0,4.0,4.0,NaN,1.0,NaN,20.0,5.0,NaN,18.0,NaN,NaN,25.0,1.0

In [32]:
temp_df.to_excel('Datasets/1-Data-Gathering/batsman_runs.xlsx')

In [36]:
# exporting with a sheet name inside an excel file
temp_df.to_excel('Datasets/1-Data-Gathering/output2.xlsx', sheet_name='runs')

In [35]:
# exporting in multiple sheets inside a single excel file
with pd.ExcelWriter('Datasets/1-Data-Gathering/output.xlsx') as writer:
    temp_df.to_excel(writer, sheet_name='Sheet_name_1')
    temp_df2.to_excel(writer, sheet_name='Sheet_name_2')